
/**
Constructor
Do not call Function in Constructor.
*/
class TestFontStyle()
{
	super();

	//TODO:edit here

}
extends AView;


function TestFontStyle*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestFontStyle*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestFontStyle*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
