
/**
Constructor
Do not call Function in Constructor.
*/
class TestTamplate()
{
	super();

	//TODO:edit here

}
extends AView;


function TestTamplate*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestTamplate*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestTamplate*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
